export const MEASURE_UNITS = [
  { label: "Case", value: "CS" },
  { label: "Each", value: "EA" },
  { label: "Pound", value: "LB" },
  { label: "Bag", value: "BG" },
  { label: "Jug", value: "JG" },
  { label: "Count", value: "CT" },
  { label: "Box", value: "BX" },
  { label: "Pack", value: "PK" },
  { label: "Carton", value: "CTN" },
  { label: "Tray", value: "TR" },
  { label: "Bottle", value: "BTL" },
  { label: "Can", value: "CAN" },
  { label: "Piece", value: "PC" },
  { label: "Dozen", value: "DZ" },
  { label: "Gallon", value: "GAL" },
  { label: "Quart", value: "QT" },
  { label: "Liter", value: "L" },
  { label: "Ounce", value: "OZ" },
] as const
