import { StyleSheet } from "@react-pdf/renderer"

const COLORS = {
  primary: "#80b83a",
  main: "#141414",
  secondary: "#676767",
  divider: "#e2e8f0",
  bgSubtle: "#f8fafc",
}

const baseStyles = {
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: COLORS.main,
    lineHeight: 1.4,
    position: "relative",
    paddingTop: 40,
    paddingLeft: 40,
    paddingRight: 40,
    paddingBottom: 60,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 20,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  logo: {
    width: 65,
    height: "auto",
  },
  docTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.main,
  },
  tagline: {
    fontSize: 10,
    color: COLORS.secondary,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  headerRight: {
    textAlign: "right",
    width: "40%",
  },
  headerContactText: {
    fontSize: 10,
  },
  sectionTitle: {
    fontSize: 9,
    fontWeight: "bold",
    backgroundColor: COLORS.bgSubtle,
    padding: "6 10",
    marginTop: 15,
    marginBottom: 10,
    color: COLORS.main,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  row: {
    flexDirection: "row",
    marginBottom: 8,
    gap: 20,
  },
  fieldGroup: {
    flex: 1,
  },
  label: {
    fontSize: 8,
    color: COLORS.secondary,
    fontWeight: 600,
    textTransform: "uppercase",
    marginBottom: 2,
    lineHeight: 1,
  },
  value: {
    fontSize: 10,
    color: "#0f172a",
    fontWeight: "bold",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.bgSubtle,
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    padding: 6,
  },
  tableHeaderText: {
    fontSize: 7,
    fontWeight: "bold",
    color: COLORS.secondary,
    textTransform: "uppercase",
    padding: "4 6",
  },
  tableRow: {
    flexDirection: "row",
    padding: "0 0",
    alignItems: "stretch",
  },
  signatureBlock: {
    width: "50%",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 5,
  },
  signatureImage: {
    width: 200,
    height: 80,
    marginBottom: 16,
    objectFit: "contain",
    objectPosition: "left",
  },
  contentText: {
    fontSize: 10,
    color: "#334155",
    textAlign: "justify",
    marginBottom: 8,
    marginTop: 10,
  },
  table: {
    width: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  tableColHeader: {
    width: "100%",
    borderRightWidth: 1,
    padding: 6,
    fontSize: 10,
    fontWeight: "bold",
  },
  tableCell: {
    minHeight: 24,
    height: "auto",
    width: "100%",
    borderRightWidth: 1,
    padding: 6,
    fontSize: 9,
    lineHeight: 1,
  },
  tableCellPacking: {
    height: "auto",
    width: "100%",
    borderRightWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
    fontSize: 8,
    lineHeight: 1,
  },
  pageNumber: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
  },
}

const applicationStyles = {
  page: {
    paddingTop: 38,
    paddingBottom: 108,
    paddingHorizontal: 36,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: COLORS.main,
    lineHeight: 1.3,
  },
  runningBrand: {
    position: "absolute",
    top: 18,
    left: 36,
    width: 250,
    height: 12,
    fontSize: 7,
    color: COLORS.secondary,
    letterSpacing: 0.7,
  },
  runningTitle: {
    position: "absolute",
    top: 18,
    left: 330,
    width: 229,
    height: 12,
    textAlign: "right",
    fontSize: 7,
    color: COLORS.secondary,
    letterSpacing: 0.7,
  },
  applicationFooterAddresses: {
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingTop: 8,
    flexDirection: "row",
    gap: 21,
  },
  footerLeft: {
    flex: 1,
    fontSize: 9,
    lineHeight: 1.5,
    color: COLORS.secondary,
    flexDirection: "column",
  },
  footerRight: {
    flex: 1,
    fontSize: 9,
    lineHeight: 1.5,
    color: COLORS.secondary,
    flexDirection: "column",
  },
  footerHeading: { fontFamily: "Helvetica-Bold", color: COLORS.main },
  footerLabel: {
    position: "absolute",
    top: 816,
    left: 36,
    width: 400,
    height: 14,
    fontSize: 6,
    color: COLORS.secondary,
  },
  pageNumber: {
    position: "absolute",
    top: 816,
    left: 469,
    width: 90,
    height: 14,
    textAlign: "right",
    fontSize: 6,
    color: COLORS.secondary,
  },
  applicationHeader: {
    borderTopWidth: 3,
    borderTopColor: COLORS.primary,
    paddingTop: 10,
    marginBottom: 10,
  },
  eyebrow: {
    fontSize: 8,
    color: COLORS.primary,
    letterSpacing: 1.8,
    marginBottom: 8,
  },
  applicationTitle: {
    fontSize: 23,
    fontFamily: "Helvetica-Bold",
    letterSpacing: -0.8,
    lineHeight: 1.15,
  },
  applicationTagline: { fontSize: 9, color: COLORS.secondary, marginTop: 4 },
  summary: {
    flexDirection: "row",
    gap: 18,
    backgroundColor: "#F5F5F5",
    padding: 9,
    marginTop: 8,
    borderRadius: 5,
  },
  applicationSectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: COLORS.main,
    marginTop: 8,
    marginBottom: 4,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  applicationRow: { flexDirection: "row", marginBottom: 4, gap: 18 },
  applicationFieldGroup: { flex: 1, minWidth: 0 },
  applicationLabel: {
    fontSize: 7,
    color: COLORS.secondary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  applicationValue: { fontSize: 9, color: COLORS.main, lineHeight: 1.3 },
  record: {
    borderLeftWidth: 2,
    borderLeftColor: COLORS.primary,
    paddingLeft: 9,
    marginBottom: 8,
  },
  legal: {
    fontSize: 9,
    color: COLORS.secondary,
    lineHeight: 1.5,
    marginBottom: 4,
  },
  signatureBlock: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    paddingBottom: 8,
  },
  signatureImage: {
    width: 150,
    height: 42,
    objectFit: "contain",
    objectPosition: "left",
    marginBottom: 8,
  },
}

const styles = StyleSheet.create({
  ...baseStyles,
  ...applicationStyles,
  header: applicationStyles.applicationHeader,
  docTitle: applicationStyles.applicationTitle,
  tagline: applicationStyles.applicationTagline,
  sectionTitle: applicationStyles.applicationSectionTitle,
  row: applicationStyles.applicationRow,
  fieldGroup: applicationStyles.applicationFieldGroup,
  label: { ...applicationStyles.applicationLabel, marginBottom: 0 },
  value: { ...applicationStyles.applicationValue },
} as any)

export { styles, COLORS }
